# Generated by Django 2.0.7 on 2018-07-22 11:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(verbose_name='Текст комментария')),
                ('comments_date', models.DateTimeField(default=datetime.datetime(2018, 7, 22, 13, 51, 48, 932744), verbose_name='Дата комментария')),
                ('сomments_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор коммента')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250, verbose_name='Имя')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценки',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('site', models.CharField(max_length=250, null=True, verbose_name='Веб-сайт')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('category', models.CharField(max_length=250, null=True, verbose_name='Категория')),
                ('next_game', models.DateField(null=True, verbose_name='Дата следующей игры')),
                ('label', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
            },
        ),
        migrations.AddField(
            model_name='criteria',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='Quiz.Quiz', verbose_name='Квизы'),
        ),
        migrations.AddField(
            model_name='comments',
            name='сomments_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm', to='Quiz.Quiz', verbose_name='Квизы'),
        ),
    ]
