# Generated by Django 2.0.7 on 2018-07-22 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 13, 56, 44, 958864), verbose_name='Дата комментария'),
        ),
    ]
