# Generated by Django 2.0.7 on 2018-07-23 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20180722_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 19, 49, 28, 643763), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='сomments_author',
            field=models.CharField(max_length=250, verbose_name='Автор'),
        ),
    ]
