# Generated by Django 2.0.7 on 2018-07-23 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20180723_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='сomments_author',
            new_name='author_com',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='сomments_quiz',
            new_name='quizz_com',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 20, 22, 12, 239482), verbose_name='Дата комментария'),
        ),
    ]
