# Generated by Django 2.0.7 on 2018-07-28 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20180724_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatesPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(null=True, verbose_name='Дата игры')),
                ('game_place', models.CharField(max_length=250, verbose_name='Автор')),
                ('game_date_registration', models.DateField(null=True, verbose_name='Дата регистрации')),
                ('for_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='Quiz.Quiz', verbose_name='Квизы')),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 12, 43, 52, 981362), verbose_name='Дата комментария'),
        ),
    ]
